---
extends:
  - eslint:recommended
env:
  node: true
rules:
  strict: [1, "global"]
  spaced-comment: 0
  no-mixed-requires: 0
  no-var: 0
  one-var: 0
  object-shorthand: 0
  prefer-arrow-callback: 0
  newline-after-var: 0
  global-require: 0
