---
printWidth: 100
tabWidth: 4
useTabs: false
semi: true
singleQuote: false
trailingComma: none
bracketSpacing: true
arrowParens: always
overrides:
  - files:
      - "*.yaml"
      - "*.yml"
      - "*.json"
    options:
      tabWidth: 2
